### ISSUE TITLE
ImportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub'

### ISSUE THREAD

**Issue by ehosseiniasl** [ZhangXInFD/SpeechTokenizer#12]
python3.10
huggingface_hub: 0.20.3

cmd:
```
from speechtokenizer import SpeechTokenizer
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ehosseiniasl/github_repos/SpeechTokenizer/speechtokenizer/__init__.py", line 2, in <module>
    from .trainer import SpeechTokenizerTrainer
  File "/home/ehosseiniasl/github_repos/SpeechTokenizer/speechtokenizer/trainer/__init__.py", line 1, in <module>
    from .trainer import SpeechTokenizerTrainer
  File "/home/ehosseiniasl/github_repos/SpeechTokenizer/speechtokenizer/trainer/trainer.py", line 20, in <module>
    from accelerate import Accelerator, DistributedType, DistributedDataParallelKwargs, DataLoaderConfiguration
  File "/home/ehosseiniasl/.local/lib/python3.10/site-packages/accelerate/__init__.py", line 16, in <module>
    from .accelerator import Accelerator
  File "/home/ehosseiniasl/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 34, in <module>
    from huggingface_hub import split_torch_state_dict_into_shards
ImportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/home/ehosseiniasl/.local/lib/python3.10/site-packages/huggingface_hub/__init__.py)
```

**Comment by ehosseiniasl** [comment]
@ZhangXInFD  could you please provide the version of following packages?
```
transformers
pytorch
```

**Comment by ehosseiniasl** [comment]
And also `accelerate` version?
